#DOCKERFILE FOR BATTLE-STATIONS INFRASTRUCTURE

#NODE JS
FROM node:7.7
RUN mkdir -p /usr/src/battle-stations/
WORKDIR /usr/src/battle-stations/
ADD package.json /usr/src/battle-stations/
RUN npm install
ADD . /usr/src/battle-stations/
