#DOCKERFILE FOR BATTLE-STATIONS INFRASTRUCTURE

#NODE JS
FROM node:7.7
RUN mkdir -p /usr/src/battle-stations/
WORKDIR /app
COPY . /app
RUN npm install
RUN npm test
EXPOSE 3000
EXPOSE 8080
CMD ["npm", "start", "&&", "tail", "-F", "/etc/hosts/" ]
